[DEFAULT]
debug = true
use_stderr = true

[auth]
methods = password,token,openid,application_credential,x509,mapped

[api_policy]
opa_base_url = unix:///var/opa/opa.sock

[webauthn]
enabled = true
driver = raft
relying_party_id = local
relying_party_origin = https://keystone.local
relying_party_name = keystone

#[interface_public]
#cluster_address = 0.0.0.0:8300

[interface_internal]
tcp_address = 0.0.0.0:8215
type = "spiffe"
trust_domains = "example.org"
