// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
#![allow(clippy::doc_paragraphs_missing_punctuation)]
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod expiring_user_group_membership;
pub mod federated_user;
pub mod group;
pub mod local_user;
pub mod nonlocal_user;
pub mod password;
pub mod sea_orm_active_enums;
pub mod user;
pub mod user_group_membership;
pub mod user_option;
