[DEFAULT]
debug = true
use_stderr = true
log_dir = /var/log/keystone

[auth]
methods = password,token,openid,application_credential,x509

[api_policy]
opa_base_url = http://localhost:8181

[webauthn]
relying_party_id = local
relying_party_origin = https://keystone.local
relying_party_name = keystone

[mapping]
cluster_salt = "fbb27433d07ab307cc1fc899d0e174cf197fd398fbcff7285a63fe2f94eec2fe"
