# Skaffold configuration for deploying keystone development environment
#
# # Requirements:
# * local registry running at `localhost:5000` when `local` profile is used
#
# # Usage
#
# `skaffold run --cleanup=false -p local --default-repo localhost:5000
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: keystone
build:
  insecureRegistries:
    - localhost:5000
  artifacts:
    - image: keystone-rs
      context: .
      docker:
        dockerfile: Dockerfile
    - image: keystone-opa
      context: .
      docker:
        dockerfile: tools/Dockerfile.opa
    - image: keystone-tests
      context: .
      docker:
        dockerfile: tools/Dockerfile.functest
  local:
    concurrency: 0

profiles:
  - name: github-ci
    build:
      local:
        useBuildkit: true
        concurrency: 0
        tryImportMissing: true
  - name: local
    build:
      insecureRegistries:
        - localhost:5000
      local:
        useDockerCLI: true
        concurrency: 0
        push: true
        #tryImportMissing: true
manifests:
  kustomize:
    paths:
      - tools/k8s/keystone/overlays/dev
  rawYaml:
    - tools/k8s/tests/k8s-auth-test-sa.yaml
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  kubectl:
    flags:
      apply: ["--wait"]
    hooks:
      after:
        - host:
            # This command will block Skaffold until the bootstrap job hits 'Completed'
            command: ["kubectl", "wait", "--for=condition=complete", "job/keystone-bootstrap", "--timeout=60s"]
  helm:
    releases:
      - name: cloudnative-pg
        repo: https://cloudnative-pg.github.io/charts
        remoteChart: cloudnative-pg
        createNamespace: true
        namespace: cnpg
verify:
  #- name: api-test
  #  container:
  #    image: keystone-tests
  #    name: api-test
  #    env:
  #      - name: KEYSTONE_URL
  #        value: http://keystone-rs.default.svc.cluster.local:8080
  #  executionMode:
  #    kubernetesCluster: {}

  - name: "k8s-auth-test"
    container:
      image: "keystone-tests"
      name: "api-test"
      command: ["/tests/test-k8s-auth", "--nocapture"]
    executionMode:
      kubernetesCluster: {}
        #jobManifestPath: tools/k8s/tests/k8s_auth_job.yaml

