# Skaffold configuration for deploying keystone development environment
#
# # Requirements:
# * local registry running at `localhost:5000` when `local` profile is used
#
# # Usage
#
# `skaffold run --cleanup=false -p local --default-repo localhost:5000
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: keystone
build:
  insecureRegistries:
    - localhost:5000
  artifacts:
    - image: keystone-rs
      context: .
      docker:
        dockerfile: Dockerfile
    - image: keystone-opa
      context: .
      docker:
        dockerfile: tools/Dockerfile.opa
    - image: keystone-tests
      context: .
      docker:
        dockerfile: tools/Dockerfile.functest

  local:
    concurrency: 0

profiles:
  - name: github-ci
    build:
      local:
        useBuildkit: true
        concurrency: 0
        tryImportMissing: true
  - name: local
    build:
      insecureRegistries:
        - localhost:5000
      local:
        useDockerCLI: true
        concurrency: 0
        push: true
        #tryImportMissing: true
manifests:
  kustomize:
    paths:
      - tools/k8s/keystone/overlays/dev
      - tools/k8s/tests/keycloak
      - tools/k8s/tests/dex
  rawYaml:
    - tools/k8s/tests/k8s-auth-test-sa.yaml
    - tools/k8s/tests/selenium.yaml
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  kubectl:
    flags:
      apply: ["--wait"]
    hooks:
      after:
        - host:
            # This command will block Skaffold until the bootstrap job hits 'Completed'
            command: ["kubectl", "wait", "--for=condition=complete", "job/keystone-bootstrap", "--timeout=180s"]
  helm:
    releases:
      - name: cloudnative-pg
        repo: https://cloudnative-pg.github.io/charts
        remoteChart: cloudnative-pg
        createNamespace: true
        namespace: cnpg
verify:
  - name: "api-test"
    container:
      image: "keystone-tests"
      name: "api-test"
      command: ["/tests/test-api"]
      env:
        - name: "KEYSTONE_URL"
          value: "http://keystone-rs.default.svc.cluster.local:8080"
        - name: "OS_AUTH_URL"
          value: "http://keystone-rs.default.svc.cluster.local:8080"
        - name: "OS_USERNAME"
          value: "admin"
        - name: "OS_PASSWORD"
          value: "password"
        - name: "OS_USER_DOMAIN_ID"
          value: "default"
        - name: "OS_PROJECT_NAME"
          value: "admin"
        - name: "OS_PROJECT_DOMAIN_ID"
          value: "default"
    executionMode:
      kubernetesCluster: {}

  - name: "k8s-auth-test"
    container:
      image: "keystone-tests"
      name: "k8s-auth-test"
      command: ["/tests/test-k8s-auth", "--nocapture"]
      env:
        - name: "KEYSTONE_URL"
          value: "http://keystone-rs.default.svc.cluster.local:8080"
        - name: "OS_AUTH_URL"
          value: "http://keystone-rs.default.svc.cluster.local:8080"
        - name: "OS_USERNAME"
          value: "admin"
        - name: "OS_PASSWORD"
          value: "password"
        - name: "OS_USER_DOMAIN_ID"
          value: "default"
        - name: "OS_PROJECT_NAME"
          value: "admin"
        - name: "OS_PROJECT_DOMAIN_ID"
          value: "default"
    executionMode:
      kubernetesCluster:
        overrides: '{ "spec": { "template": { "spec": { "serviceAccountName": "keystone-k8s-auth-test-sa" } } } }'

  - name: "keycloak"
    container:
      image: "keystone-tests"
      name: "keycloak"
      command: ["/tests/test-keycloak", "--nocapture"]
      env:
        - name: "BROWSERDRIVER_URL"
          value: "http://selenium-service:4444"
        - name: "KEYSTONE_URL"
          value: "http://keystone-rs:8080"
        - name: "KEYCLOAK_URL"
          value: "http://keycloak:8080"
        - name: "KEYCLOAK_PASSWORD"
          value: "admin"
    executionMode:
      kubernetesCluster: {}

  # - name: "dex"
  #   container:
  #     image: "keystone-tests"
  #     name: "dex-test"
  #     command: ["/tests/test-dex", "--nocapture"]
  #     #env:
  #     #  - name: "BROWSERDRIVER_URL"
  #     #    value: "http://selenium-service:4444"
  #     #  - name: "KEYSTONE_URL"
  #     #    value: "http://keystone-rs:8080"
  #     #  - name: "DEX_URL"
  #     #    value: "http://dex:5556"
  #   executionMode:
  #     kubernetesCluster:
  #       #jobManifestPath: "tools/k8s/tests/dex/job.yaml"
  #       overrides: '{ "spec": { "template": { "spec": { "containers": [{"name": "dex", "image": "ghcr.io/dexidp/dex:latest"}, {"name": "test", "image": "keystone-tests"}] } } } }'
