// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! # Error
//!
//! Diverse errors that can occur during the Keystone processing (not the API).
use thiserror::Error;

use crate::application_credential::ApplicationCredentialProviderError;
use crate::assignment::AssignmentProviderError;
use crate::catalog::CatalogProviderError;
use crate::federation::FederationProviderError;
use crate::identity::IdentityProviderError;
use crate::identity_mapping::IdentityMappingProviderError;
use crate::k8s_auth::K8sAuthProviderError;
use crate::resource::ResourceProviderError;
use crate::revoke::RevokeProviderError;
use crate::role::RoleProviderError;
use crate::token::TokenProviderError;
use crate::trust::TrustProviderError;

/// Builder error.
///
/// A wrapper error that is used instead of the error generated by the
/// `derive_builder`.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum BuilderError {
    /// Uninitialized field.
    #[error("{0}")]
    UninitializedField(String),
    /// Custom validation error.
    #[error("{0}")]
    Validation(String),
}

impl From<String> for BuilderError {
    fn from(s: String) -> Self {
        Self::Validation(s)
    }
}

impl From<derive_builder::UninitializedFieldError> for BuilderError {
    fn from(ufe: derive_builder::UninitializedFieldError) -> Self {
        Self::UninitializedField(ufe.to_string())
    }
}

/// Keystone error.
#[derive(Debug, Error)]
pub enum KeystoneError {
    /// Application credential provider.
    #[error(transparent)]
    ApplicationCredential {
        /// The source of the error.
        #[from]
        source: ApplicationCredentialProviderError,
    },

    /// Assignment provider.
    #[error(transparent)]
    AssignmentProvider {
        /// The source of the error.
        #[from]
        source: AssignmentProviderError,
    },

    /// Catalog provider.
    #[error(transparent)]
    CatalogProvider {
        /// The source of the error.
        #[from]
        source: CatalogProviderError,
    },

    /// Federation provider.
    #[error(transparent)]
    FederationProvider {
        /// The source of the error.
        #[from]
        source: FederationProviderError,
    },

    /// Identity provider.
    #[error(transparent)]
    IdentityProvider {
        /// The source of the error.
        #[from]
        source: IdentityProviderError,
    },

    /// Identity mapping provider.
    #[error(transparent)]
    IdentityMapping {
        /// The source of the error.
        #[from]
        source: IdentityMappingProviderError,
    },

    /// IO error.
    #[error(transparent)]
    IO {
        /// The source of the error.
        #[from]
        source: std::io::Error,
    },

    /// Json serialization error.
    #[error("json serde error: {}", source)]
    Json {
        /// The source of the error.
        #[from]
        source: serde_json::Error,
    },

    /// K8s auth provider.
    #[error(transparent)]
    K8sAuthProvider {
        /// The source of the error.
        #[from]
        source: K8sAuthProviderError,
    },

    /// Policy engine is not available.
    #[error("policy enforcement is requested, but not available with the enabled features")]
    PolicyEnforcementNotAvailable,

    /// Raft storage is not available.
    #[error("raft storage is not available")]
    RaftNotAvailable,

    /// Resource provider.
    #[error(transparent)]
    ResourceProvider {
        /// The source of the error.
        #[from]
        source: ResourceProviderError,
    },

    /// Revoke provider error.
    #[error(transparent)]
    RevokeProvider {
        /// The source of the error.
        #[from]
        source: RevokeProviderError,
    },

    /// Role provider.
    #[error(transparent)]
    RoleProvider {
        /// The source of the error.
        #[from]
        source: RoleProviderError,
    },

    /// Token provider.
    #[error(transparent)]
    TokenProvider {
        /// The source of the error.
        #[from]
        source: TokenProviderError,
    },

    /// Trust provider.
    #[error(transparent)]
    TrustProvider {
        /// The source of the error.
        #[from]
        source: TrustProviderError,
    },

    /// Url parsing error.
    #[error(transparent)]
    UrlParse {
        #[from]
        source: url::ParseError,
    },

    #[error("provider error: {}", source)]
    Provider {
        #[source]
        source: Box<dyn std::error::Error + Send + Sync + 'static>,
    },
}
