// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! v4 user CRUD helpers, generated with [`crate::macros::crud_endpoint`].
//!
//! `/v4/users` is served by its own handlers
//! (`crates/keystone/src/api/v4/user/`), not by the v3 router — only the
//! request/response types are shared (`crates/api-types/src/v4/user.rs`
//! re-exports the v3 ones). These helpers therefore mirror
//! [`crate::identity::user`] but target `api_version = (4, 0)`.

use openstack_keystone_api_types::v4::user::*;
// `v4::user` re-exports `UserUpdateRequest` but not the `UserUpdate` it
// wraps, so the patch type comes from `v3` directly. The two are the same
// type either way.
use openstack_keystone_api_types::v3::group::Group;
use openstack_keystone_api_types::v3::project::ProjectShort;
use openstack_keystone_api_types::v3::user::UserUpdate;

use crate::macros::crud_endpoint;

crud_endpoint! {
    create {
        request = UserV4CreateApiRequest,
        func = create_user_v4,
        path = "users",
        body_key = "user",
        create_type = UserCreate,
        model = User,
        response_key = "user",
        service = Identity,
        api_version = (4, 0),
    }
    show {
        request = UserV4ShowApiRequest,
        func = get_user_v4,
        path = "users",
        model = User,
        response_key = "user",
        service = Identity,
        api_version = (4, 0),
    }
    // `update_put`: `crates/keystone/src/api/v4/user/update.rs` declares
    // `put`, unlike the v3 handler's `patch`.
    update_put {
        request = UserV4UpdateApiRequest,
        func = update_user_v4,
        path = "users",
        body_key = "user",
        update_type = UserUpdate,
        model = User,
        response_key = "user",
        service = Identity,
        api_version = (4, 0),
    }
    list {
        request = UserV4ListRequest,
        func = list_users_v4,
        path = "users",
        model = User,
        response_key = "users",
        service = Identity,
        api_version = (4, 0),
        query = [domain_id, name, unique_id, enabled],
    }
    // `delete_fn`, not `delete`: `v3::user::User` already carries the
    // `DeletableResource` impl generated by `crate::identity::user`.
    delete_fn {
        request = UserV4DeleteApiRequest,
        func = delete_user_v4,
        path = "users",
        service = Identity,
        api_version = (4, 0),
    }
    // `GET /v4/users/{user_id}/groups`: a sub-resource collection, so it
    // takes the `parent` form and has no query parameters of its own.
    list {
        request = UserV4GroupsRequest,
        func = list_user_groups_v4,
        parent = ("users", user_id),
        path = "groups",
        model = Group,
        response_key = "groups",
        service = Identity,
        api_version = (4, 0),
        query = [],
    }
    // `GET /v4/users/{user_id}/projects`.
    list {
        request = UserV4ProjectsRequest,
        func = list_user_projects_v4,
        parent = ("users", user_id),
        path = "projects",
        model = ProjectShort,
        response_key = "projects",
        service = Identity,
        api_version = (4, 0),
        query = [],
    }
}
