// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
#![allow(unused_imports)]

pub use super::federated_auth_state::Entity as FederatedAuthState;
pub use super::federated_identity_provider::Entity as FederatedIdentityProvider;
pub use super::federated_mapping::Entity as FederatedMapping;
//pub use super::federated_user::Entity as FederatedUser;
pub use super::federation_protocol::Entity as FederationProtocol;
pub use super::identity_provider::Entity as IdentityProvider;
pub use super::idp_remote_ids::Entity as IdpRemoteIds;
pub use super::mapping::Entity as Mapping;
