apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: keystone-rs
  name: keystone-rs
spec:
  replicas: 1
  serviceName: keystone-rs-internal
  selector:
    matchLabels:
      app.kubernetes.io/name: keystone-rs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keystone-rs
    spec:
      initContainers:
        - name: db-waiter
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo "Waiting for PostgreSQL to be available..."; while ! nc -z -w 1 keystone-db-rw 5432; do echo "Still waiting for postgres-service..."; sleep 2; done; echo "PostgreSQL is available! Starting application."']

        - name: identity-generator
          image: busybox
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: raft-config-shared
              mountPath: /etc/keystone
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Extract the u64 ID
              NODE_ID=$(echo $POD_NAME | grep -o '[0-9]\+$')

              # Write the identity file
              cat <<EOF > /etc/keystone/site.toml
              [distributed_storage]
              node_id = $NODE_ID
              cluster_addr = "https://$POD_NAME.keystone-rs-internal.default.svc.cluster.local:8300"
              path = "/storage"
              tls_client_ca_file = "/certs/ca.crt"
              tls_cert_file = "/certs/tls.crt"
              tls_key_file = "/certs/tls.key"
              EOF
      containers:
        - env:
            - name: OS_DATABASE__CONNECTION
              valueFrom:
                secretKeyRef:
                  key: fqdn-uri
                  name: keystone-db-app
            - name: KEYSTONE_SITE_VARS_FILE
              value: "/etc/keystone/site.toml"
          command: ["keystone", "-vv"]

          image: keystone-rs
          name: keystone
          ports:
            - containerPort: 8080
              name: keystone-rs
              protocol: TCP
            - containerPort: 8300
              name: keystone-raft
              protocol: TCP

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: keystone-rs
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: keystone-rs
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 600
            httpGet:
              path: /
              port: keystone-rs
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/keystone/fernet-keys
              name: fernet
            - mountPath: /certs
              name: keystone-tls
              readOnly: true
            - mountPath: /etc/keystone
              name: raft-config-shared
            - mountPath: /storage
              name: raft-storage
            - mountPath: /etc/keystone/keystone.conf
              name: config
              subPath: keystone.conf
              readOnly: true

        - command: ["opa", "run", "--server", "/policy", "--addr", ":8181", "--log-level", "debug"]
          image: opa
          name: opa
          ports:
            - containerPort: 8181
              name: http

      volumes:
        - name: config
          configMap:
            name: keystone
        - name: config-opa
          configMap:
            name: keystone-opa
        - name: fernet
          secret:
            defaultMode: 420
            optional: false
            secretName: fernet-keys
            items:
              - key: "k0"
                path: "0"
              - key: "k1"
                path: "1"
        - name: keystone-tls
          secret:
            defaultMode: 420
            optional: false
            secretName: keystone-peer-tls
        - name: raft-storage
          emptyDir: {}
        - name: raft-config-shared
          emptyDir: {}
