// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! Database management commands for keystone-manage.

use std::io;

use async_trait::async_trait;
use clap::{Parser, Subcommand};
use color_eyre::{Report, eyre::WrapErr, eyre::eyre};
use eyre::Result;
use sea_orm::ConnectOptions;
use sea_orm::ConnectionTrait;
use sea_orm::Database;
use sea_orm::DatabaseConnection;
use sea_orm_migration::MigrationTrait;
use sea_orm_migration::MigratorTrait;
use secrecy::ExposeSecret;
use tracing::info;
use tracing_subscriber::{
    filter::{LevelFilter, Targets},
    prelude::*,
};

use openstack_keystone_config::Config;
use openstack_keystone_core::SqlDriverRegistration;

// Force inventory::submit! sections from each plugin crate to remain
// linked. openstack_keystone::_ANCHORS is generated by build.rs which
// discovers all openstack-keystone-* dependencies from Cargo.toml and
// creates a #[used] static referencing each crate's anchor() function.
// This chain ensures the linker extracts all archive members containing
// inventory::submit! sections.
#[used]
static _INVENTORY_LINK: &[fn()] = openstack_keystone::_ANCHORS;

use crate::PerformAction;

/// Collect all migrations from registered SQL drivers.
fn collect_migrations() -> Vec<Box<dyn MigrationTrait>> {
    let mut migrations: Vec<Box<dyn MigrationTrait>> = Vec::new();

    for registration in inventory::iter::<SqlDriverRegistration> {
        for mig in registration.driver.migrations() {
            migrations.push(mig);
        }
    }

    migrations.sort_by(|a, b| a.name().cmp(b.name()));
    migrations
}

/// Migrator that collects migrations from all registered SqlDrivers.
struct CompositeMigrator;

#[async_trait]
impl MigratorTrait for CompositeMigrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        collect_migrations()
    }
}

/// Database management commands.
#[derive(Parser)]
pub struct DbCommand {
    /// Verbosity level. Repeat to increase level.
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,

    #[command(subcommand)]
    command: DbCommands,
}

#[derive(Subcommand)]
enum DbCommands {
    /// Setup the initial database schema from entity definitions.
    ///
    /// Creates tables from the SeaORM entity definitions registered by each
    /// SQL driver. This should be run for a fresh database.
    Sync,

    /// Apply pending migrations.
    Up {
        /// Number of pending migrations to apply.
        #[arg(short('n'))]
        steps: Option<u32>,
    },

    /// Rollback applied migrations.
    Down {
        /// Number of migrations to rollback.
        #[arg(short('n'))]
        steps: Option<u32>,
    },

    /// Check the status of all migrations.
    Status,

    /// Drop all tables from the database, then reapply all migrations.
    Fresh,

    /// Rollback all applied migrations, then reapply all migrations.
    Refresh,

    /// Rollback all applied migrations.
    Reset,
}

fn setup_logging(verbose: u8) {
    let filter = Targets::new().with_default(match verbose {
        0 => LevelFilter::WARN,
        1 => LevelFilter::INFO,
        2 => LevelFilter::DEBUG,
        _ => LevelFilter::TRACE,
    });

    let log_layer = tracing_subscriber::fmt::layer()
        .with_writer(io::stderr)
        .with_filter(filter);

    tracing_subscriber::registry().with(log_layer).init();
}

async fn connect_db(config: &Config) -> Result<DatabaseConnection> {
    let secret = config.database.get_connection();
    let conn_url = secret.expose_secret().to_string();

    let opt = ConnectOptions::new(conn_url).sqlx_logging(false).to_owned();

    Database::connect(opt)
        .await
        .wrap_err("Database connection failed")
}

#[allow(clippy::print_stdout)]
#[async_trait]
impl PerformAction for DbCommand {
    async fn take_action(self, config: &Config) -> Result<(), Report> {
        setup_logging(self.verbose);
        let conn = connect_db(config).await?;

        match self.command {
            DbCommands::Sync => {
                sync_schema(&conn).await?;
                println!("schema sync completed successfully");
                Ok(())
            }

            DbCommands::Up { steps } => {
                info!("Applying pending migrations...");
                CompositeMigrator::up(&conn, steps).await?;
                println!("pending migrations applied");
                Ok(())
            }

            DbCommands::Down { steps } => {
                info!("Rolling back migrations...");
                CompositeMigrator::down(&conn, steps).await?;
                println!("migrations rolled back");
                Ok(())
            }

            DbCommands::Status => {
                let pending = CompositeMigrator::get_pending_migrations(&conn).await?;
                if pending.is_empty() {
                    println!("No pending migrations!");
                } else {
                    println!("Pending migrations:");
                    for mig in &pending {
                        println!("  {}", mig.name());
                    }
                }

                let applied = CompositeMigrator::get_applied_migrations(&conn).await?;
                println!("Applied migrations:");
                for mig in &applied {
                    println!("  {}", mig.name());
                }
                Ok(())
            }

            DbCommands::Fresh => {
                info!("Dropping all tables and reapplying migrations...");
                CompositeMigrator::fresh(&conn).await?;
                println!("database refreshed");
                Ok(())
            }

            DbCommands::Refresh => {
                info!("Rolling back and reapplying all migrations...");
                CompositeMigrator::refresh(&conn).await?;
                println!("database refreshed");
                Ok(())
            }

            DbCommands::Reset => {
                info!("Rolling back all migrations...");
                CompositeMigrator::reset(&conn).await?;
                println!("all migrations rolled back");
                Ok(())
            }
        }
    }
}

async fn sync_schema(db: &DatabaseConnection) -> Result<(), Report> {
    let schema = sea_orm::Schema::new(db.get_database_backend());

    for (i, driver) in inventory::iter::<SqlDriverRegistration>
        .into_iter()
        .enumerate()
    {
        info!("Setting up schema for driver {}", i + 1);
        driver
            .driver
            .setup(db, &schema)
            .await
            .wrap_err_with(|| eyre!("failed to setup schema for SQL driver"))?;
    }

    Ok(())
}
