// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! # OAuth2 browser session provider API.

use async_trait::async_trait;

use openstack_keystone_core_types::oauth2_session::{
    AuthorizationCode, PreAuthSession, RefreshToken,
};

use crate::keystone::ServiceState;
use crate::oauth2_session::Oauth2SessionProviderError;

/// Input to [`Oauth2SessionApi::start_pre_auth_session`]. `session_id` and
/// the CSRF-derivation secret are generated by the service, not the
/// caller.
#[derive(Debug, Clone)]
pub struct StartPreAuthSessionRequest {
    /// Domain the `/authorize` request targets.
    pub domain_id: String,
    /// Requesting `OAuth2Client.client_id`.
    pub client_id: String,
    /// Validated (allowlisted) redirect URI.
    pub redirect_uri: String,
    /// Requested scope values.
    pub scope: Vec<String>,
    /// Client-supplied `state`.
    pub state: String,
    /// PKCE `code_challenge`.
    pub code_challenge: String,
    /// PKCE `code_challenge_method`.
    pub code_challenge_method: String,
    /// OIDC `nonce`.
    pub nonce: Option<String>,
}

/// Input to [`Oauth2SessionApi::issue_authorization_code`]. The code value
/// itself is generated by the service.
#[derive(Debug, Clone)]
pub struct IssueAuthorizationCodeRequest {
    /// Owning domain.
    pub domain_id: String,
    /// The `OAuth2Client.client_id` this code is issued to.
    pub client_id: String,
    /// The authenticated principal's `user_id`.
    pub user_id: String,
    /// Redirect URI recorded at `/authorize`.
    pub redirect_uri: String,
    /// PKCE `code_challenge`.
    pub code_challenge: String,
    /// PKCE `code_challenge_method`.
    pub code_challenge_method: String,
    /// Granted scope values.
    pub scope: Vec<String>,
    /// OIDC `nonce`.
    pub nonce: Option<String>,
    /// Epoch seconds of primary authentication.
    pub auth_time: i64,
    /// Authentication methods references.
    pub amr: Vec<String>,
}

/// Input to [`Oauth2SessionApi::issue_refresh_token`] (family root) --
/// `token_id`/bearer value are generated by the service.
#[derive(Debug, Clone)]
pub struct IssueRefreshTokenRequest {
    /// Owning domain.
    pub domain_id: String,
    /// The `OAuth2Client.client_id` this family belongs to.
    pub client_id: String,
    /// The authenticated principal's `user_id`.
    pub user_id: String,
    /// The scope grant this family carries.
    pub scope: Vec<String>,
}

/// Outcome of [`Oauth2SessionApi::redeem_refresh_token`] (ADR 0026 §9).
#[derive(Debug, Clone)]
pub enum RefreshTokenRedemption {
    /// Normal rotation: the presented token was the family's live leaf.
    /// The old token is now `spent_at`-stamped and a new leaf has been
    /// minted in the same family.
    Rotated {
        /// The newly minted leaf record.
        record: RefreshToken,
        /// The newly minted leaf's plaintext bearer value.
        bearer: String,
    },
    /// The presented token was already spent, outside the reuse grace
    /// window (`[oauth2] refresh_token_reuse_grace_minutes`) -- an active
    /// breach signal. The entire family has been revoked as a side effect
    /// of this call; the caller is responsible for the ADR §9 critical
    /// audit dispatch.
    ReuseDetected {
        /// The family that was just revoked.
        family_id: String,
    },
    /// The presented token does not resolve to any known, unexpired
    /// record (unknown, already-revoked-family, or past
    /// `refresh_token_lifetime_days`).
    Invalid,
}

/// The trait for the OAuth2 browser session provider (ADR 0026 §10 Phase
/// 4): pre-auth session, authorization code, and refresh token family
/// lifecycle, including the reuse-detection state machine.
#[async_trait]
pub trait Oauth2SessionApi: Send + Sync {
    /// Create a new pre-auth browser session at `GET /authorize`.
    async fn start_pre_auth_session(
        &self,
        state: &ServiceState,
        req: StartPreAuthSessionRequest,
    ) -> Result<PreAuthSession, Oauth2SessionProviderError>;

    /// Fetch a pre-auth session. Returns `Ok(None)` for a missing or
    /// expired session (expiry is enforced here, lazily, on read).
    async fn get_pre_auth_session(
        &self,
        state: &ServiceState,
        session_id: &str,
    ) -> Result<Option<PreAuthSession>, Oauth2SessionProviderError>;

    /// Stamp `user_id`/`auth_time` once login succeeds.
    async fn mark_authenticated(
        &self,
        state: &ServiceState,
        session_id: &str,
        user_id: &str,
        auth_time: i64,
    ) -> Result<PreAuthSession, Oauth2SessionProviderError>;

    /// Stamp `consent_granted` once the consent step completes.
    async fn mark_consent(
        &self,
        state: &ServiceState,
        session_id: &str,
        granted: bool,
    ) -> Result<PreAuthSession, Oauth2SessionProviderError>;

    /// Delete the pre-auth session (single-flight completion).
    async fn complete_pre_auth_session(
        &self,
        state: &ServiceState,
        session_id: &str,
    ) -> Result<(), Oauth2SessionProviderError>;

    /// Mint a single-use authorization code at the end of a successful
    /// consent step. Returns the plaintext code value.
    async fn issue_authorization_code(
        &self,
        state: &ServiceState,
        req: IssueAuthorizationCodeRequest,
    ) -> Result<String, Oauth2SessionProviderError>;

    /// Redeem (fetch-and-invalidate) an authorization code at `/token`.
    /// Returns `Ok(None)` if the code is unknown, already redeemed, or
    /// expired -- a second redemption of the same code never returns
    /// `Some` twice.
    async fn redeem_authorization_code(
        &self,
        state: &ServiceState,
        code: &str,
    ) -> Result<Option<AuthorizationCode>, Oauth2SessionProviderError>;

    /// Mint the root of a new `refresh_token` family. Returns the record
    /// and its plaintext bearer value (shown to the caller exactly once,
    /// mirroring `OAuth2ClientResource.client_secret_hash`'s posture).
    async fn issue_refresh_token(
        &self,
        state: &ServiceState,
        req: IssueRefreshTokenRequest,
    ) -> Result<(RefreshToken, String), Oauth2SessionProviderError>;

    /// Redeem a presented `refresh_token` bearer value: rotates it if it
    /// was the family's live leaf, or triggers reuse-detection breach
    /// containment if it was already spent outside the grace window (ADR
    /// 0026 §9).
    async fn redeem_refresh_token(
        &self,
        state: &ServiceState,
        presented_bearer: &str,
    ) -> Result<RefreshTokenRedemption, Oauth2SessionProviderError>;
}
