// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! # Filesystem-backed [`AsymmetricKeySource`] (ADR 0026 §10, Phase 0)
//!
//! On-disk layout for the `Primary` role is Python-Keystone-compatible:
//! `private.pem` (PKCS#8 PEM) / `public.pem` (SubjectPublicKeyInfo PEM) in
//! the configured directory, the same names `keystone-manage
//! create_jws_keypair` writes — so filesystem keys shared with Python
//! Keystone nodes work unchanged. `Previous`/`Pending` (used only by
//! keystone-rs's own multi-generational bookkeeping; Python's JWS provider
//! has no such concept) are stored as `previous_private.pem`/
//! `previous_public.pem` and `pending_private.pem`/`pending_public.pem`.
//!
//! Python's on-disk format carries no algorithm metadata (it only ever
//! writes ES256 keypairs), so a keypair with no sidecar `<prefix>algorithm`
//! file is assumed `ES256` for Python-compatibility. Keys generated by
//! this source itself always write that sidecar, so a `keystone-rs`-only
//! deployment using `RS256` round-trips its algorithm choice correctly.
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use secrecy::{ExposeSecret, SecretBox};
use tokio::sync::broadcast;
use tokio::task::spawn_blocking;

use crate::asymmetric::source::{AsymmetricKeySource, KeyMaterial, KeyRole, SigningAlgorithm};
use crate::error::KeyRepositoryError;

fn prefix_for(role: KeyRole) -> &'static str {
    match role {
        KeyRole::Primary => "",
        KeyRole::Previous => "previous_",
        KeyRole::Pending => "pending_",
    }
}

fn io_err(source: std::io::Error, path: PathBuf) -> KeyRepositoryError {
    KeyRepositoryError::Io { source, path }
}

/// The asymmetric (ES256/RS256) key repository on the local filesystem.
pub struct FilesystemAsymmetricKeySource {
    key_repository: PathBuf,
    change_tx: broadcast::Sender<()>,
}

impl FilesystemAsymmetricKeySource {
    /// Create a new source. No background watcher — the JWS driver reloads
    /// on-demand; callers that need change notifications can wire their own
    /// polling and call [`Self::subscribe`]'s sender indirectly via a future
    /// watched variant if that becomes necessary.
    #[must_use]
    pub fn new(key_repository: PathBuf) -> Self {
        let (change_tx, _) = broadcast::channel(16);
        Self {
            key_repository,
            change_tx,
        }
    }

    fn private_path(&self, role: KeyRole) -> PathBuf {
        self.key_repository
            .join(format!("{}private.pem", prefix_for(role)))
    }

    fn public_path(&self, role: KeyRole) -> PathBuf {
        self.key_repository
            .join(format!("{}public.pem", prefix_for(role)))
    }

    fn algorithm_path(&self, role: KeyRole) -> PathBuf {
        self.key_repository
            .join(format!("{}algorithm", prefix_for(role)))
    }

    fn read_role_blocking(
        dir: &Path,
        role: KeyRole,
    ) -> Result<Option<KeyMaterial>, KeyRepositoryError> {
        let this = FilesystemAsymmetricKeySource::new(dir.to_path_buf());
        let private_path = this.private_path(role);
        let public_path = this.public_path(role);

        if !private_path.exists() || !public_path.exists() {
            return Ok(None);
        }

        let private_pem =
            std::fs::read_to_string(&private_path).map_err(|e| io_err(e, private_path.clone()))?;
        let public_pem =
            std::fs::read_to_string(&public_path).map_err(|e| io_err(e, public_path.clone()))?;

        let private_key_der = pem::parse(&private_pem)
            .map_err(|e| KeyRepositoryError::Crypto(format!("invalid private key PEM: {e}")))?
            .into_contents();
        let public_key_der = pem::parse(&public_pem)
            .map_err(|e| KeyRepositoryError::Crypto(format!("invalid public key PEM: {e}")))?
            .into_contents();

        let algorithm_path = this.algorithm_path(role);
        let algorithm = match std::fs::read_to_string(&algorithm_path) {
            Ok(contents) => match contents.trim() {
                "RS256" => SigningAlgorithm::Rs256,
                _ => SigningAlgorithm::Es256,
            },
            // No sidecar: a Python-Keystone-authored keypair, always ES256.
            Err(_) => SigningAlgorithm::Es256,
        };

        let kid = crate::asymmetric::kid::derive_kid(&public_key_der);
        let created_at: DateTime<Utc> = std::fs::metadata(&private_path)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
            .and_then(|d| DateTime::<Utc>::from_timestamp(d.as_secs() as i64, d.subsec_nanos()))
            .unwrap_or_else(Utc::now);

        Ok(Some(KeyMaterial {
            algorithm,
            private_key_der: SecretBox::new(Box::new(private_key_der)),
            public_key_der,
            kid,
            created_at,
        }))
    }

    fn write_role_blocking(
        dir: &Path,
        role: KeyRole,
        material: &KeyMaterial,
    ) -> Result<(), KeyRepositoryError> {
        std::fs::create_dir_all(dir).map_err(|e| io_err(e, dir.to_path_buf()))?;
        let this = FilesystemAsymmetricKeySource::new(dir.to_path_buf());

        let private_pem = pem::encode(&pem::Pem::new(
            "PRIVATE KEY",
            material.private_key_der.expose_secret().clone(),
        ));
        let public_pem = pem::encode(&pem::Pem::new(
            "PUBLIC KEY",
            material.public_key_der.clone(),
        ));

        let private_path = this.private_path(role);
        std::fs::write(&private_path, private_pem).map_err(|e| io_err(e, private_path.clone()))?;
        let public_path = this.public_path(role);
        std::fs::write(&public_path, public_pem).map_err(|e| io_err(e, public_path.clone()))?;
        let algorithm_path = this.algorithm_path(role);
        let algorithm_str = match material.algorithm {
            SigningAlgorithm::Es256 => "ES256",
            SigningAlgorithm::Rs256 => "RS256",
        };
        std::fs::write(&algorithm_path, algorithm_str)
            .map_err(|e| io_err(e, algorithm_path.clone()))?;
        Ok(())
    }

    fn remove_role_blocking(dir: &Path, role: KeyRole) -> Result<(), KeyRepositoryError> {
        let this = FilesystemAsymmetricKeySource::new(dir.to_path_buf());
        for path in [
            this.private_path(role),
            this.public_path(role),
            this.algorithm_path(role),
        ] {
            match std::fs::remove_file(&path) {
                Ok(()) => {}
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => return Err(io_err(e, path)),
            }
        }
        Ok(())
    }
}

#[async_trait]
impl AsymmetricKeySource for FilesystemAsymmetricKeySource {
    async fn load(&self) -> Result<BTreeMap<KeyRole, KeyMaterial>, KeyRepositoryError> {
        let dir = self.key_repository.clone();
        let error_dir = dir.clone();
        spawn_blocking(move || {
            let mut out = BTreeMap::new();
            for role in [KeyRole::Primary, KeyRole::Previous, KeyRole::Pending] {
                if let Some(material) = Self::read_role_blocking(&dir, role)? {
                    out.insert(role, material);
                }
            }
            Ok(out)
        })
        .await
        .map_err(|e| KeyRepositoryError::Io {
            source: std::io::Error::other(e),
            path: error_dir,
        })?
    }

    async fn write(&self, role: KeyRole, material: &KeyMaterial) -> Result<(), KeyRepositoryError> {
        let dir = self.key_repository.clone();
        let error_dir = dir.clone();
        let material = material.clone();
        spawn_blocking(move || Self::write_role_blocking(&dir, role, &material))
            .await
            .map_err(|e| KeyRepositoryError::Io {
                source: std::io::Error::other(e),
                path: error_dir,
            })?
    }

    async fn remove(&self, role: KeyRole) -> Result<(), KeyRepositoryError> {
        let dir = self.key_repository.clone();
        let error_dir = dir.clone();
        spawn_blocking(move || Self::remove_role_blocking(&dir, role))
            .await
            .map_err(|e| KeyRepositoryError::Io {
                source: std::io::Error::other(e),
                path: error_dir,
            })?
    }

    fn subscribe(&self) -> broadcast::Receiver<()> {
        self.change_tx.subscribe()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::asymmetric::keygen::generate_keypair;

    #[tokio::test]
    async fn test_write_load_roundtrip_es256() {
        let dir = tempfile::tempdir().unwrap();
        let source = FilesystemAsymmetricKeySource::new(dir.path().to_path_buf());
        let material = generate_keypair(SigningAlgorithm::Es256).unwrap();

        source.write(KeyRole::Primary, &material).await.unwrap();
        let loaded = source.load().await.unwrap();
        let primary = loaded.get(&KeyRole::Primary).unwrap();
        assert_eq!(primary.kid, material.kid);
        assert_eq!(primary.algorithm, SigningAlgorithm::Es256);
        assert_eq!(primary.public_key_der, material.public_key_der);
    }

    #[tokio::test]
    async fn test_write_load_roundtrip_rs256() {
        let dir = tempfile::tempdir().unwrap();
        let source = FilesystemAsymmetricKeySource::new(dir.path().to_path_buf());
        let material = generate_keypair(SigningAlgorithm::Rs256).unwrap();

        source.write(KeyRole::Primary, &material).await.unwrap();
        let loaded = source.load().await.unwrap();
        let primary = loaded.get(&KeyRole::Primary).unwrap();
        assert_eq!(primary.algorithm, SigningAlgorithm::Rs256);
    }

    #[tokio::test]
    async fn test_load_on_unconfigured_directory_is_empty() {
        let dir = tempfile::tempdir().unwrap();
        let source = FilesystemAsymmetricKeySource::new(dir.path().join("does-not-exist"));
        assert!(source.load().await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn test_python_authored_keypair_has_no_algorithm_sidecar_defaults_to_es256() {
        let dir = tempfile::tempdir().unwrap();
        let material = generate_keypair(SigningAlgorithm::Es256).unwrap();
        // Simulate a Python-Keystone-authored `create_jws_keypair` output:
        // only `private.pem`/`public.pem`, no `algorithm` sidecar.
        let private_pem = pem::encode(&pem::Pem::new(
            "PRIVATE KEY",
            secrecy::ExposeSecret::expose_secret(&material.private_key_der).clone(),
        ));
        let public_pem = pem::encode(&pem::Pem::new(
            "PUBLIC KEY",
            material.public_key_der.clone(),
        ));
        std::fs::write(dir.path().join("private.pem"), private_pem).unwrap();
        std::fs::write(dir.path().join("public.pem"), public_pem).unwrap();

        let source = FilesystemAsymmetricKeySource::new(dir.path().to_path_buf());
        let loaded = source.load().await.unwrap();
        assert_eq!(loaded.len(), 1);
        let primary = loaded.get(&KeyRole::Primary).unwrap();
        assert_eq!(primary.algorithm, SigningAlgorithm::Es256);
        // No Previous/Pending files present, matching Python's single-key model.
        assert!(!loaded.contains_key(&KeyRole::Previous));
        assert!(!loaded.contains_key(&KeyRole::Pending));
    }

    #[tokio::test]
    async fn test_remove_missing_role_is_not_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let source = FilesystemAsymmetricKeySource::new(dir.path().to_path_buf());
        source.remove(KeyRole::Previous).await.unwrap();
    }

    #[tokio::test]
    async fn test_promote_pending_to_primary_default_impl() {
        let dir = tempfile::tempdir().unwrap();
        let source = FilesystemAsymmetricKeySource::new(dir.path().to_path_buf());
        let old_primary = generate_keypair(SigningAlgorithm::Es256).unwrap();
        source.write(KeyRole::Primary, &old_primary).await.unwrap();
        let pending = generate_keypair(SigningAlgorithm::Es256).unwrap();
        source.write(KeyRole::Pending, &pending).await.unwrap();

        source.promote_pending_to_primary().await.unwrap();

        let loaded = source.load().await.unwrap();
        assert_eq!(loaded.get(&KeyRole::Primary).unwrap().kid, pending.kid);
        assert_eq!(loaded.get(&KeyRole::Previous).unwrap().kid, old_primary.kid);
        assert!(!loaded.contains_key(&KeyRole::Pending));
    }
}
