// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
#![allow(unused_imports)]

pub use super::endpoint::Entity as Endpoint;
pub use super::endpoint_group::Entity as EndpointGroup;
pub use super::project_endpoint::Entity as ProjectEndpoint;
pub use super::project_endpoint_group::Entity as ProjectEndpointGroup;
pub use super::region::Entity as Region;
pub use super::service::Entity as Service;
