// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trust")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub trustor_user_id: String,
    pub trustee_user_id: String,
    pub project_id: Option<String>,
    pub impersonation: bool,
    pub deleted_at: Option<DateTime>,
    pub expires_at: Option<DateTime>,
    pub remaining_uses: Option<u32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extra: Option<String>,
    pub expires_at_int: Option<i64>,
    pub redelegated_trust_id: Option<String>,
    pub redelegation_count: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::trust_role::Entity")]
    TrustRole,
}

impl ActiveModelBehavior for ActiveModel {}

impl Related<super::trust_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrustRole.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::trust_role::Relation::Role.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::trust_role::Relation::Trust.def().rev())
    }
}
