// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

#[cfg(test)]
use derive_builder::Builder;
use serde::Deserialize;

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "user")]
#[cfg_attr(test, derive(Default))]
#[cfg_attr(test, derive(Builder))]
#[cfg_attr(test, builder(setter(strip_option, into)))]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    #[cfg_attr(test, builder(default))]
    pub extra: Option<String>,
    #[cfg_attr(test, builder(default))]
    pub enabled: Option<bool>,
    #[cfg_attr(test, builder(default))]
    pub default_project_id: Option<String>,
    #[cfg_attr(test, builder(default))]
    pub created_at: Option<DateTime>,
    #[cfg_attr(test, builder(default))]
    pub last_active_at: Option<Date>,
    pub domain_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::expiring_user_group_membership::Entity")]
    ExpiringUserGroupMembership,
    #[sea_orm(has_many = "super::federated_user::Entity")]
    FederatedUser,
    #[sea_orm(has_one = "super::local_user::Entity")]
    LocalUser,
    #[sea_orm(has_one = "super::nonlocal_user::Entity")]
    NonlocalUser,
    #[sea_orm(has_many = "super::user_group_membership::Entity")]
    UserGroupMembership,
    #[sea_orm(has_many = "super::user_option::Entity")]
    UserOption,
}

impl Related<super::expiring_user_group_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpiringUserGroupMembership.def()
    }
}

impl Related<super::federated_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedUser.def()
    }
}

impl Related<super::local_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocalUser.def()
    }
}

impl Related<super::nonlocal_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NonlocalUser.def()
    }
}

impl Related<super::user_group_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGroupMembership.def()
    }
}

impl Related<super::user_option::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserOption.def()
    }
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_group_membership::Relation::Group.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_group_membership::Relation::User.def().rev())
    }
}

impl Related<super::password::Entity> for Entity {
    fn to() -> RelationDef {
        super::local_user::Relation::Password.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::local_user::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
