// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "application_credential")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub internal_id: i32,
    pub id: String,
    pub name: String,
    pub secret_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub user_id: String,
    pub project_id: Option<String>,
    pub expires_at: Option<i64>,
    pub system: Option<String>,
    pub unrestricted: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application_credential_access_rule::Entity")]
    ApplicationCredentialAccessRule,
    #[sea_orm(has_many = "super::application_credential_role::Entity")]
    ApplicationCredentialRole,
}

impl Related<super::application_credential_access_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationCredentialAccessRule.def()
    }
}

impl Related<super::application_credential_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationCredentialRole.def()
    }
}

impl Related<super::access_rule::Entity> for Entity {
    fn to() -> RelationDef {
        super::application_credential_access_rule::Relation::AccessRule.def()
    }

    fn via() -> Option<RelationDef> {
        Some(
            super::application_credential_access_rule::Relation::ApplicationCredential
                .def()
                .rev(),
        )
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        super::application_credential_role::Relation::Role.def()
    }

    fn via() -> Option<RelationDef> {
        Some(
            super::application_credential_role::Relation::ApplicationCredential
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
