//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "federated_auth_state")]
pub struct Model {
    pub idp_id: String,
    pub mapping_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub state: String,
    pub nonce: String,
    pub redirect_uri: String,
    pub pkce_verifier: String,
    pub expires_at: DateTime,
    pub requested_scope: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::federated_identity_provider::Entity",
        from = "Column::IdpId",
        to = "super::federated_identity_provider::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FederatedIdentityProvider,
    #[sea_orm(
        belongs_to = "super::federated_mapping::Entity",
        from = "Column::MappingId",
        to = "super::federated_mapping::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FederatedMapping,
}

impl Related<super::federated_identity_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedIdentityProvider.def()
    }
}

impl Related<super::federated_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedMapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
