//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

#[cfg(test)]
use derive_builder::Builder;

use super::sea_orm_active_enums::MappingType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "federated_mapping")]
#[cfg_attr(test, derive(Builder))]
#[cfg_attr(test, builder(setter(strip_option, into)))]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub idp_id: String,
    pub domain_id: Option<String>,
    pub r#type: MappingType,
    #[cfg_attr(test, builder(default))]
    pub enabled: bool,
    pub allowed_redirect_uris: Option<String>,
    pub user_id_claim: String,
    pub user_name_claim: String,
    pub domain_id_claim: Option<String>,
    pub groups_claim: Option<String>,
    pub bound_audiences: Option<String>,
    pub bound_subject: Option<String>,
    pub bound_claims: Option<Json>,
    pub oidc_scopes: Option<String>,
    pub token_project_id: Option<String>,
    pub token_restriction_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::federated_identity_provider::Entity",
        from = "Column::IdpId",
        to = "super::federated_identity_provider::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FederatedIdentityProvider,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::DomainId",
        to = "super::project::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Project,
}

impl Related<super::federated_identity_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedIdentityProvider.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
