// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kubernetes_auth_role")]
pub struct Model {
    pub auth_instance_id: String,

    pub bound_audience: Option<String>,

    #[sea_orm(column_type = "Text")]
    pub bound_service_account_names: Option<String>,

    #[sea_orm(column_type = "Text")]
    pub bound_service_account_namespaces: Option<String>,

    pub domain_id: String,

    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,

    pub enabled: bool,

    pub name: String,

    pub token_restriction_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kubernetes_auth_instance::Entity",
        from = "Column::AuthInstanceId",
        to = "super::kubernetes_auth_instance::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    KubernetesAuthInstance,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::DomainId",
        to = "super::project::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Project,
    #[sea_orm(
        belongs_to = "super::token_restriction::Entity",
        from = "Column::TokenRestrictionId",
        to = "super::token_restriction::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TokenRestriction,
}

impl Related<super::kubernetes_auth_instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubernetesAuthInstance.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::token_restriction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenRestriction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
