// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kubernetes_auth")]
pub struct Model {
    #[sea_orm(column_type = "Text", nullable)]
    pub ca_cert: Option<String>,

    pub domain_id: String,

    pub enabled: bool,

    pub host: String,

    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,

    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::kubernetes_auth_role::Entity")]
    KubernetesAuthRole,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::DomainId",
        to = "super::project::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Project,
}

impl Related<super::kubernetes_auth_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubernetesAuthRole.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
