// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
#![allow(unused_imports)]

pub use super::access_rule::Entity as AccessRule;
pub use super::access_token::Entity as AccessToken;
pub use super::alembic_version::Entity as AlembicVersion;
pub use super::application_credential::Entity as ApplicationCredential;
pub use super::application_credential_access_rule::Entity as ApplicationCredentialAccessRule;
pub use super::application_credential_role::Entity as ApplicationCredentialRole;
pub use super::assignment::Entity as Assignment;
pub use super::config_register::Entity as ConfigRegister;
pub use super::consumer::Entity as Consumer;
pub use super::credential::Entity as Credential;
pub use super::endpoint::Entity as Endpoint;
pub use super::endpoint_group::Entity as EndpointGroup;
pub use super::expiring_user_group_membership::Entity as ExpiringUserGroupMembership;
pub use super::federated_auth_state::Entity as FederatedAuthState;
pub use super::federated_identity_provider::Entity as FederatedIdentityProvider;
pub use super::federated_mapping::Entity as FederatedMapping;
pub use super::federated_user::Entity as FederatedUser;
pub use super::federation_protocol::Entity as FederationProtocol;
pub use super::group::Entity as Group;
pub use super::id_mapping::Entity as IdMapping;
pub use super::identity_provider::Entity as IdentityProvider;
pub use super::idp_remote_ids::Entity as IdpRemoteIds;
pub use super::implied_role::Entity as ImpliedRole;
pub use super::limit::Entity as Limit;
pub use super::local_user::Entity as LocalUser;
pub use super::mapping::Entity as Mapping;
pub use super::nonlocal_user::Entity as NonlocalUser;
pub use super::password::Entity as Password;
pub use super::policy::Entity as Policy;
pub use super::policy_association::Entity as PolicyAssociation;
pub use super::project::Entity as Project;
pub use super::project_endpoint::Entity as ProjectEndpoint;
pub use super::project_endpoint_group::Entity as ProjectEndpointGroup;
pub use super::project_option::Entity as ProjectOption;
pub use super::project_tag::Entity as ProjectTag;
pub use super::region::Entity as Region;
pub use super::registered_limit::Entity as RegisteredLimit;
pub use super::request_token::Entity as RequestToken;
pub use super::revocation_event::Entity as RevocationEvent;
pub use super::role::Entity as Role;
pub use super::role_option::Entity as RoleOption;
pub use super::sensitive_config::Entity as SensitiveConfig;
pub use super::service::Entity as Service;
pub use super::service_provider::Entity as ServiceProvider;
pub use super::system_assignment::Entity as SystemAssignment;
pub use super::token::Entity as Token;
pub use super::token_restriction::Entity as TokenRestriction;
pub use super::token_restriction_role_association::Entity as TokenRestrictionRoleAssociation;
pub use super::trust::Entity as Trust;
pub use super::trust_role::Entity as TrustRole;
pub use super::user::Entity as User;
pub use super::user_group_membership::Entity as UserGroupMembership;
pub use super::user_option::Entity as UserOption;
pub use super::webauthn_credential::Entity as WebauthnCredential;
pub use super::webauthn_state::Entity as WebauthnState;
pub use super::whitelisted_config::Entity as WhitelistedConfig;
