experimental = ["setup-scripts"]

[profile.default]
# exclude raft-only tests
default-filter = 'not test(/spiffe/) and not test(/mapping/) and not test(/test_cluster/) and not test(/api_key/)'
# Global default settings
#
[scripts.setup.setup-pg]
command = { command-line = [ "tools/setup-db.sh", "postgres" ] }

[scripts.setup.setup-mysql]
command = { command-line = [ "tools/setup-db.sh", "mysql" ] }

[scripts.setup.teardown]
command = { command-line = [ "tools/teardown-db.sh" ] }

[scripts.setup.raft-env]
command = { command-line = [ "tools/raft-env.sh" ] }

[scripts.setup.start-api]
command = { command-line = [ "tools/start-api.sh" ] }


[profile.ci]
inherits = "default"

[profile.ci.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true

# --- POSTGRES PROFILE ---
[profile.postgres]

[[profile.postgres.scripts]]
filter = "binary(api)"
setup = "setup-pg"
[[profile.postgres.scripts]]
filter = "binary(integration)"
setup = "setup-pg"
[[profile.postgres.scripts]]
filter = "binary(provider)"
setup = "setup-pg"

[profile.ci-postgres]
inherits = "postgres"
[profile.ci-postgres.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true

# --- MYSQL PROFILE ---
[profile.mysql]

[[profile.mysql.scripts]]
filter = "binary(api)"
setup = "setup-mysql"
[[profile.mysql.scripts]]
filter = "binary(integration)"
setup = "setup-mysql"
[[profile.mysql.scripts]]
filter = "binary(provider)"
setup = "setup-mysql"

[profile.ci-mysql]
inherits = "mysql"
[profile.ci-mysql.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true

# --- Raft based integration test ---
[profile.raft]
default-filter = "all()"

[[profile.raft.scripts]]
filter = "binary(integration) + binary(test_cluster)"
setup = "raft-env"

[profile.ci-raft]
inherits = "raft"
[profile.ci-raft.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true

# --- API tests ---
[profile.api]
#default-filter = "binary(integration_api_v3) + binary(integration_api_v4)"

[[profile.api.scripts]]
filter = "binary(integration_api_v3) + binary(integration_api_v4)"
setup = "start-api"

[profile.ci-api]
inherits = "api"
[[profile.ci-api.scripts]]
filter = "binary(integration_api_v3) + binary(integration_api_v4)"
setup = "start-api"
[profile.ci-api.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true
