// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Build script that discovers all openstack-keystone-* plugin
//! dependencies and generates an anchors static to keep their
//! inventory::submit! sections linked.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let cargo_toml = Path::new(&manifest_dir).join("Cargo.toml");
    let content = fs::read_to_string(&cargo_toml).unwrap();

    let parsed: toml::Value = toml::from_str(&content)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {}", cargo_toml.display(), e));

    let deps = parsed
        .get("dependencies")
        .and_then(|v| v.as_table())
        .expect("Cargo.toml must have a [dependencies] section");

    let mut plugin_deps = Vec::new();

    for key in deps.keys() {
        // Only include openstack-keystone-* crates
        if !key.starts_with("openstack-keystone-") {
            continue;
        }

        // Only anchor driver crates and webauthn
        if !key.contains("-driver-") && !key.starts_with("openstack-keystone-webauthn") {
            continue;
        }

        // Convert hyphens to underscores for Rust crate name
        plugin_deps.push(key.replace('-', "_"));
    }

    plugin_deps.sort();

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_file = Path::new(&out_dir).join("inventory_anchors.rs");

    let mut s = String::new();
    s.push_str(
        "// Generated by build.rs — DO NOT EDIT.\n\
         // Force inventory::submit! sections from each plugin crate to remain linked.\n\n\
         #[used]\n\
         pub static _ANCHORS: &[fn()] = &[\n",
    );
    for dep in &plugin_deps {
        s.push_str(&format!("    {dep}::anchor,\n"));
    }
    s.push_str("];\n");

    fs::write(&out_file, s).unwrap();
    println!("cargo::rerun-if-changed={}", cargo_toml.display());
}
