// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
//! # Error
//!
//! Diverse errors that can occur during the Keystone processing (not the API).
use thiserror::Error;

use crate::application_credential::error::*;
use crate::assignment::error::*;
use crate::catalog::error::*;
use crate::federation::error::*;
use crate::identity::error::*;
use crate::policy::*;
use crate::resource::error::*;
use crate::revoke::error::*;
use crate::token::TokenProviderError;
use crate::trust::TrustError;

/// Keystone error.
#[derive(Debug, Error)]
pub enum KeystoneError {
    /// Application credential provider.
    #[error(transparent)]
    ApplicationCredential {
        /// The source of the error.
        #[from]
        source: ApplicationCredentialProviderError,
    },

    /// Assignment provider.
    #[error(transparent)]
    AssignmentError {
        /// The source of the error.
        #[from]
        source: AssignmentProviderError,
    },

    /// Catalog provider.
    #[error(transparent)]
    CatalogError {
        /// The source of the error.
        #[from]
        source: CatalogProviderError,
    },

    /// Federation provider.
    #[error(transparent)]
    FederationError {
        /// The source of the error.
        #[from]
        source: FederationProviderError,
    },

    /// Identity provider.
    #[error(transparent)]
    IdentityError {
        /// The source of the error.
        #[from]
        source: IdentityProviderError,
    },

    /// IO error.
    #[error(transparent)]
    IO {
        /// The source of the error.
        #[from]
        source: std::io::Error,
    },

    /// Json serialization error.
    #[error("json serde error: {}", source)]
    JsonError {
        /// The source of the error.
        #[from]
        source: serde_json::Error,
    },

    /// Policy engine.
    #[error(transparent)]
    Policy {
        /// The source of the error.
        #[from]
        source: PolicyError,
    },

    /// Policy engine is not available.
    #[error("policy enforcement is requested, but not available with the enabled features")]
    PolicyEnforcementNotAvailable,

    /// Resource provider.
    #[error(transparent)]
    ResourceError {
        /// The source of the error.
        #[from]
        source: ResourceProviderError,
    },

    /// Revoke provider error.
    #[error(transparent)]
    RevokeProvider {
        /// The source of the error.
        #[from]
        source: RevokeProviderError,
    },

    /// Token provider.
    #[error(transparent)]
    TokenProvider {
        /// The source of the error.
        #[from]
        source: TokenProviderError,
    },

    /// Trust provider.
    #[error(transparent)]
    TrustProvider {
        /// The source of the error.
        #[from]
        source: TrustError,
    },

    /// Url parsing error.
    #[error(transparent)]
    UrlParse {
        #[from]
        source: url::ParseError,
    },

    /// WebauthN error.
    #[error("webauthn error: {}", source)]
    Webauthn {
        /// The source of the error.
        #[from]
        source: webauthn_rs::prelude::WebauthnError,
    },
}

/// Builder error.
///
/// A wrapper error that is used instead of the error generated by the
/// `derive_builder`.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum BuilderError {
    /// Uninitialized field
    #[error("{0}")]
    UninitializedField(String),
    /// Custom validation error
    #[error("{0}")]
    ValidationError(String),
}

impl From<String> for BuilderError {
    fn from(s: String) -> Self {
        Self::ValidationError(s)
    }
}

impl From<derive_builder::UninitializedFieldError> for BuilderError {
    fn from(ufe: derive_builder::UninitializedFieldError) -> Self {
        Self::UninitializedField(ufe.to_string())
    }
}

/// Context aware database error.
#[derive(Debug, Error)]
pub enum DatabaseError {
    /// Conflict.
    #[error("{message} while {context}")]
    Conflict {
        /// The error message.
        message: String,
        /// The error context.
        context: String,
    },

    /// SqlError.
    #[error("{message} while {context}")]
    Sql {
        /// The error message.
        message: String,
        /// The error context.
        context: String,
    },

    /// Database error.
    #[error("Database error while {context}")]
    Database {
        /// The source of the error.
        source: sea_orm::DbErr,
        /// The error context.
        context: String,
    },
}

pub trait DbContextExt<T> {
    fn context(self, msg: impl Into<String>) -> Result<T, DatabaseError>;
}

impl<T> DbContextExt<T> for Result<T, sea_orm::DbErr> {
    fn context(self, context: impl Into<String>) -> Result<T, DatabaseError> {
        self.map_err(|err| match err.sql_err() {
            Some(sea_orm::SqlErr::UniqueConstraintViolation(descr)) => DatabaseError::Conflict {
                message: descr.to_string(),
                context: context.into(),
            },
            Some(sea_orm::SqlErr::ForeignKeyConstraintViolation(descr)) => {
                DatabaseError::Conflict {
                    message: descr.to_string(),
                    context: context.into(),
                }
            }
            Some(other) => DatabaseError::Sql {
                message: other.to_string(),
                context: context.into(),
            },
            None => DatabaseError::Database {
                source: err,
                context: context.into(),
            },
        })
    }
}
