// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4
pub use super::expiring_user_group_membership::Entity as ExpiringUserGroupMembership;
pub use super::federated_user::Entity as FederatedUser;
pub use super::group::Entity as Group;
pub use super::local_user::Entity as LocalUser;
pub use super::nonlocal_user::Entity as NonlocalUser;
pub use super::password::Entity as Password;
pub use super::user::Entity as User;
pub use super::user_group_membership::Entity as UserGroupMembership;
pub use super::user_option::Entity as UserOption;
