name: Benchmarks

permissions:
  contents: read

on:
  pull_request:
    branches: "main"
    paths:
      - '.github/workflows/benchmark*.yml'
      - 'Cargo.toml'
      - 'benches/**'
      - 'crates/**'

env:
  CARGO_TERM_COLOR: always
  KEYSTONE_DEV_KEK: 4242424242424242424242424242424242424242424242424242424242424242
  KEYSTONE_ALLOW_ENV_KEK: "1"

jobs:
  bench_pr_branch:
    # DO NOT REMOVE: For handling Fork PRs see Pull Requests from Forks
    if: "github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' && github.actor != 'openstack-experimental-release-plz'"
    permissions:
      pull-requests: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install protobuf-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libtss2-dev pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - uses: bencherdev/bencher@main

      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project keystone \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "$GITHUB_HEAD_REF" \
          --start-point "$GITHUB_BASE_REF" \
          --start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed ${{ matrix.os }} \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --adapter rust_criterion \
          cargo bench --features bench_internals
