name: OPA policy

on:
  pull_request:
    paths:
      - 'policy/**'
      - '.github/workflows/policy-container.yml'
  push:
    branches: [ "main"]
  workflow_dispatch: # Allow manual triggering

env:
  OPA_VERSION: 1.6.0
  ORAS_VERSION: 1.2.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: ${{ env.OPA_VERSION }}

      - name: Test OPA policies
        run: opa test policy

      - name: Build policy bundle
        run: opa build policy --bundle

  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: ${{ env.OPA_VERSION }}

      - name: Setup ORAS CLI
        uses: oras-project/setup-oras@38de303aac69abb66f3e6255b7198bff35f323e3 # v2.0.0
        with:
          version: ${{ env.ORAS_VERSION }}

      - name: Build policy container
        run: opa build policy --bundle

      - name: Create empty container config
        run: echo "{}" > config.json

      - name: Log in to GitHub Container Registry for ORAS
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push policy
        run: oras push ghcr.io/${{ github.repository }}/opa-bundle:${{ github.ref_name }},latest --config config.json:application/vnd.oci.image.config.v1+json bundle.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
